package com.xsimple.im.db.greendao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.xsimple.im.db.datatable.IMChat;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "im_chat_new".
*/
public class IMChatDao extends AbstractDao<IMChat, Long> {

    public static final String TABLENAME = "im_chat_new";

    /**
     * Properties of entity IMChat.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UId = new Property(1, String.class, "uId", false, "U_ID");
        public final static Property SenderOrTarget1 = new Property(2, String.class, "senderOrTarget1", false, "SENDER_OR_TARGET1");
        public final static Property ReceiverName = new Property(3, String.class, "receiverName", false, "RECEIVER_NAME");
        public final static Property SenderOrTarget2 = new Property(4, String.class, "senderOrTarget2", false, "SENDER_OR_TARGET2");
        public final static Property Type = new Property(5, int.class, "type", false, "TYPE");
        public final static Property Name = new Property(6, String.class, "name", false, "NAME");
        public final static Property UnReadCount = new Property(7, int.class, "UnReadCount", false, "UN_READ_COUNT");
        public final static Property Time = new Property(8, Long.class, "time", false, "TIME");
        public final static Property IsStick = new Property(9, boolean.class, "isStick", false, "IS_STICK");
        public final static Property IsNotDisturb = new Property(10, boolean.class, "isNotDisturb", false, "IS_NOT_DISTURB");
        public final static Property Drafts = new Property(11, String.class, "drafts", false, "DRAFTS");
        public final static Property RefreshTime = new Property(12, long.class, "refreshTime", false, "REFRESH_TIME");
        public final static Property FunKey = new Property(13, String.class, "funKey", false, "FUN_KEY");
    }

    private DaoSession daoSession;

    private Query<IMChat> iMUser_IMChatsQuery;

    public IMChatDao(DaoConfig config) {
        super(config);
    }
    
    public IMChatDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"im_chat_new\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"U_ID\" TEXT," + // 1: uId
                "\"SENDER_OR_TARGET1\" TEXT," + // 2: senderOrTarget1
                "\"RECEIVER_NAME\" TEXT," + // 3: receiverName
                "\"SENDER_OR_TARGET2\" TEXT," + // 4: senderOrTarget2
                "\"TYPE\" INTEGER NOT NULL ," + // 5: type
                "\"NAME\" TEXT," + // 6: name
                "\"UN_READ_COUNT\" INTEGER NOT NULL ," + // 7: UnReadCount
                "\"TIME\" INTEGER," + // 8: time
                "\"IS_STICK\" INTEGER NOT NULL ," + // 9: isStick
                "\"IS_NOT_DISTURB\" INTEGER NOT NULL ," + // 10: isNotDisturb
                "\"DRAFTS\" TEXT," + // 11: drafts
                "\"REFRESH_TIME\" INTEGER NOT NULL ," + // 12: refreshTime
                "\"FUN_KEY\" TEXT);"); // 13: funKey
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"im_chat_new\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, IMChat entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uId = entity.getUId();
        if (uId != null) {
            stmt.bindString(2, uId);
        }
 
        String senderOrTarget1 = entity.getSenderOrTarget1();
        if (senderOrTarget1 != null) {
            stmt.bindString(3, senderOrTarget1);
        }
 
        String receiverName = entity.getReceiverName();
        if (receiverName != null) {
            stmt.bindString(4, receiverName);
        }
 
        String senderOrTarget2 = entity.getSenderOrTarget2();
        if (senderOrTarget2 != null) {
            stmt.bindString(5, senderOrTarget2);
        }
        stmt.bindLong(6, entity.getType());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(7, name);
        }
        stmt.bindLong(8, entity.getUnReadCount());
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(9, time);
        }
        stmt.bindLong(10, entity.getIsStick() ? 1L: 0L);
        stmt.bindLong(11, entity.getIsNotDisturb() ? 1L: 0L);
 
        String drafts = entity.getDrafts();
        if (drafts != null) {
            stmt.bindString(12, drafts);
        }
        stmt.bindLong(13, entity.getRefreshTime());
 
        String funKey = entity.getFunKey();
        if (funKey != null) {
            stmt.bindString(14, funKey);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, IMChat entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uId = entity.getUId();
        if (uId != null) {
            stmt.bindString(2, uId);
        }
 
        String senderOrTarget1 = entity.getSenderOrTarget1();
        if (senderOrTarget1 != null) {
            stmt.bindString(3, senderOrTarget1);
        }
 
        String receiverName = entity.getReceiverName();
        if (receiverName != null) {
            stmt.bindString(4, receiverName);
        }
 
        String senderOrTarget2 = entity.getSenderOrTarget2();
        if (senderOrTarget2 != null) {
            stmt.bindString(5, senderOrTarget2);
        }
        stmt.bindLong(6, entity.getType());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(7, name);
        }
        stmt.bindLong(8, entity.getUnReadCount());
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(9, time);
        }
        stmt.bindLong(10, entity.getIsStick() ? 1L: 0L);
        stmt.bindLong(11, entity.getIsNotDisturb() ? 1L: 0L);
 
        String drafts = entity.getDrafts();
        if (drafts != null) {
            stmt.bindString(12, drafts);
        }
        stmt.bindLong(13, entity.getRefreshTime());
 
        String funKey = entity.getFunKey();
        if (funKey != null) {
            stmt.bindString(14, funKey);
        }
    }

    @Override
    protected final void attachEntity(IMChat entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public IMChat readEntity(Cursor cursor, int offset) {
        IMChat entity = new IMChat( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // uId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // senderOrTarget1
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // receiverName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // senderOrTarget2
            cursor.getInt(offset + 5), // type
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // name
            cursor.getInt(offset + 7), // UnReadCount
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // time
            cursor.getShort(offset + 9) != 0, // isStick
            cursor.getShort(offset + 10) != 0, // isNotDisturb
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // drafts
            cursor.getLong(offset + 12), // refreshTime
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13) // funKey
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, IMChat entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSenderOrTarget1(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setReceiverName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSenderOrTarget2(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setType(cursor.getInt(offset + 5));
        entity.setName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUnReadCount(cursor.getInt(offset + 7));
        entity.setTime(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setIsStick(cursor.getShort(offset + 9) != 0);
        entity.setIsNotDisturb(cursor.getShort(offset + 10) != 0);
        entity.setDrafts(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setRefreshTime(cursor.getLong(offset + 12));
        entity.setFunKey(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(IMChat entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(IMChat entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(IMChat entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "IMChats" to-many relationship of IMUser. */
    public List<IMChat> _queryIMUser_IMChats(String uId) {
        synchronized (this) {
            if (iMUser_IMChatsQuery == null) {
                QueryBuilder<IMChat> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UId.eq(null));
                iMUser_IMChatsQuery = queryBuilder.build();
            }
        }
        Query<IMChat> query = iMUser_IMChatsQuery.forCurrentThread();
        query.setParameter(0, uId);
        return query.list();
    }

}
