package com.networkengine.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.networkengine.database.table.FileRecord;
import com.networkengine.database.table.Member;

import com.networkengine.database.greendao.FileRecordDao;
import com.networkengine.database.greendao.MemberDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileRecordDaoConfig;
    private final DaoConfig memberDaoConfig;

    private final FileRecordDao fileRecordDao;
    private final MemberDao memberDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileRecordDaoConfig = daoConfigMap.get(FileRecordDao.class).clone();
        fileRecordDaoConfig.initIdentityScope(type);

        memberDaoConfig = daoConfigMap.get(MemberDao.class).clone();
        memberDaoConfig.initIdentityScope(type);

        fileRecordDao = new FileRecordDao(fileRecordDaoConfig, this);
        memberDao = new MemberDao(memberDaoConfig, this);

        registerDao(FileRecord.class, fileRecordDao);
        registerDao(Member.class, memberDao);
    }
    
    public void clear() {
        fileRecordDaoConfig.clearIdentityScope();
        memberDaoConfig.clearIdentityScope();
    }

    public FileRecordDao getFileRecordDao() {
        return fileRecordDao;
    }

    public MemberDao getMemberDao() {
        return memberDao;
    }

}
