package com.networkengine.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.networkengine.database.table.Member;
import com.networkengine.database.table.FileRecord;

import com.networkengine.database.greendao.MemberDao;
import com.networkengine.database.greendao.FileRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memberDaoConfig;
    private final DaoConfig fileRecordDaoConfig;

    private final MemberDao memberDao;
    private final FileRecordDao fileRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memberDaoConfig = daoConfigMap.get(MemberDao.class).clone();
        memberDaoConfig.initIdentityScope(type);

        fileRecordDaoConfig = daoConfigMap.get(FileRecordDao.class).clone();
        fileRecordDaoConfig.initIdentityScope(type);

        memberDao = new MemberDao(memberDaoConfig, this);
        fileRecordDao = new FileRecordDao(fileRecordDaoConfig, this);

        registerDao(Member.class, memberDao);
        registerDao(FileRecord.class, fileRecordDao);
    }
    
    public void clear() {
        memberDaoConfig.clearIdentityScope();
        fileRecordDaoConfig.clearIdentityScope();
    }

    public MemberDao getMemberDao() {
        return memberDao;
    }

    public FileRecordDao getFileRecordDao() {
        return fileRecordDao;
    }

}
